##spring.data.mongodb.host=localhost
##spring.data.mongodb.port=27017
#spring.data.mongodb.uri= mongodb+srv://anshumansingh12457:Mongo21@mongodatabase.27sxwx5.mongodb.net/?appName=MongoDatabase
#spring.data.mongodb.database=journaldb
##spring.data.mongodb.username=journaldb
##spring.data.mongodb.password=journaldb
#spring.data.mongodb.auto-index-creation=true
##server.port=8081
##server.servlet.context-path=/journal








# Required connection configs for Kafka producer, consumer, and admin

spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.bootstrap-servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='2VCMYYON373WS7MZ' password='cflt+bEhtFnpNJnN4UKjaOpF46oxc9fu5x3ECW7iRAcKYfJcpZFALw9R1BzPhr6w';
spring.kafka.properties.security.protocol=SASL_SSL

# Best practice for higher availability in Apache Kafka clients prior to 3.0
spring.kafka.properties.session.timeout.ms=45000
#
#client.id=ccloud-springboot-client-f41f001a-1b55-42ac-8aed-81386060f851
